[project]
name = "avito-candidate-gen"
version = "0.1.0"
description = "Candidate generation for Avito's service search: based on a short text query, it selects up to 50 relevant listings from the database for subsequent ranking."
readme = "README.md"
authors = [
    { name = "Xogan", email = "yarok2005@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "bm25>=0.3.11",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "pymorphy3>=2.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
